### ISSUE TITLE
pac3 multiwearing 

### ISSUE THREAD

**Issue by Python1320** [Metastruct/pac3#12]
fix pac outfit transmission so that they don't get transmitted to you when you haven't even requested them yet plus don't get double transmissions on join

**Comment by notcake** [comment]
here be dragons

**Comment by notcake** [comment]
also make pac stop using net.WriteTable for outfits

**Comment by Noiwex** [comment]
Yeah, better add hundreds of glib dependencies.

**Comment by PotcFdk** [comment]
@notcake That sounds like a good idea.
@Noiwex That sounds like a bad idea and exaggerated.
