### ISSUE TITLE
Entity not passed to SetSubMaterial

### ISSUE THREAD

**Issue by LUModder** [Metastruct/pac3#13]
With SetSubMaterial, it is not being passed on an entity, thus calling a nil function.

**Comment by notcake** [comment]
what

**Comment by LUModder** [comment]
The function is ent:SetSubMaterial() but it's being called as just SetSubMaterial.

**Comment by notcake** [comment]
where

**Comment by LUModder** [comment]
Okay, nvm, I'll try to get the error if I see it again.
