### ISSUE TITLE
Invisible Custom Models (obj file)?

### ISSUE THREAD

**Issue by Vuthakral** [Metastruct/pac3#21]
Not sure what causes this issue, I'm not a lua coder. I just recently updated PAC3 and noticed that all of the sudden all of my custom models were invisible whenever a material was applied to them. Without a material they seem to work fine. Just to check my idea, I put in a backup of an older version of PAC3 that I had and it seems to work fine again. My Graphics Card is an NVIDIA Geforce 660 TI, if that might help at all.
Side note: This was on my server I had the addon installed that caused this issue, not on my client.

**Comment by thegrb93** [comment]
You should give an example pac to replicate the issue with so they can find out what is wrong.

**Comment by LUModder** [comment]
This has been noted as objcache causing the problem as Caps's repo works fine.

**Comment by suchipi** [comment]
Caps' repo uses objcache now though...

**Comment by LUModder** [comment]
Haven't updated my server in a while, so either way, we might be screwed, but hopefully not, as I'm the only one who doesn't have problems.

**Comment by Vuthakral** [comment]
How is it objcache causing the issue? The older revision I'm using has objcache but it seems to work fine.

**Comment by LUModder** [comment]
Again, I have no idea exactly what is causing the problem as I don't have any but everyone else has problems.

**Comment by SpiralP** [comment]
what pac version are you using on your server Flex? did you checkout the 'active' branch of this repo?

**Comment by edunad** [comment]
Sadly most servers that use GIT use the master version and have no idea about the active branch, i still think we should make this the master version.

**Comment by SpiralP** [comment]
does svn choose the default branch or master? most people probably would use svn over git :v

**Comment by edunad** [comment]
master i think

**Comment by suchipi** [comment]
Actually, 'active' seems to be the default checkout now. I think Python was the one who set that up.
The reason we don't use master as our place is because the standard way of handling forks on github is to keep master the same as origin/master. Believe it or not this /does/ help when merging back into origin.

**Comment by LUModder** [comment]
@SpiralP Our server was using Meta's active and then we switched over to Caps's repo after players had problems and just left it like that.

**Comment by SpiralP** [comment]
so why make issue on this repo!!!

**Comment by LUModder** [comment]
Because this is the only one having the problem

**Comment by PotcFdk** [comment]
@SpiralP if I understood @LUModder's answer correctly, he said that they had issues with the active branch and thus switched to master in order to fix it (?).
Assuming that's correct, making an issue on this repo doesn't seem that wrong to me. Am I missing something?

**Comment by SpiralP** [comment]
ah, I thought he meant it started to act up when he switched to Caps', and that it could already have been fixed on this repo

**Comment by LUModder** [comment]
So now this problem has transfered onto Caps', welp, now it doesn't even matter so.

**Comment by user4992** [comment]
I've done some 'research' on this, hoping to shed some light on the issue at hand.

At first every .obj model has the "..." text, followed by the "Downloading" text showing for a second or so before disappearing. I've noticed the following behaviour on my PAC, which uses urlOBJs with material parts applied to them, and took those screenshots on FlexBox 2, which runs the latest update of Caps' build. The issue appeared there with said update.

![pac issue](https://cloud.githubusercontent.com/assets/11893952/7334257/c0566020-eb64-11e4-8b8d-1c0bd9962de8.jpg)

That said, this is just my(client's) perspective, and it may have been showing differently for other players.

In addition, I did not encounter this issue at all when running a local server.

**Comment by LUModder** [comment]
@user4992 Was this before I restarted it and changed it to Meta branch?

**Comment by user4992** [comment]
@LUModder 

I did the screenies before the restart. I'll check again shortly.

**Comment by LUModder** [comment]
I don't know why everyone is having problems but me

![](http://i.imgur.com/V5fk0E9.png)

**Comment by user4992** [comment]
@LUModder 

Checked again. Meta's branch shows the same behaviour for me.

**Comment by GigiSpahz** [comment]
I think the "force cs model entity" on the pac3 setting is what causes the problems, enabling it does fix objs, but it also generates more problems like rendering issues on mdl that has transludent on.
I think it'd be better if i show the problem myself : https://www.dropbox.com/sc/w0rj75whg97kqon/AACYb7uQmFeJvFT5b2SVT1-Ha
